### ISSUE TITLE
No windows support

### ISSUE THREAD

**Issue by voltflake** [tristanisham/clr#1]
I tried out ZVM and noticed that help menu was broken. A quick look at source guided me here so posting an issue for it.
![image](https://user-images.githubusercontent.com/51025847/206827844-b290894a-074f-40dc-b1b9-4384bcd267b0.png)
Looks like these color codes doesn't work for windows systems (

**Comment by tristanisham** [comment]
Hey @danyildiabin,

The color codes do work on Windows, just not in Command Prompt. If you use PowerShell >7 they should work perfectly.
![image](https://user-images.githubusercontent.com/23124818/206967120-a8d17534-d5f4-4c51-8375-dc1a3b1ca129.png)

Still, I can see how that is annoying. I'll see what I can do to make colors optional so you don't have to see that 😊.

**Comment by tristanisham** [comment]
Oh my god. Oops! I thought this was the ZVM repo! My bad! Still, for ZVM there's a new update where you can turn colors off. I'll work on making a global fix through color though in the meantime! Thanks for raising this issue! @danyildiabin

**Comment by tristanisham** [comment]
@danyildiabin While I work on this, here's a ZVM update to fix your problem! https://github.com/tristanisham/zvm/releases/tag/v0.1.2

**Comment by voltflake** [comment]
> The color codes do work on Windows, just not in Command Prompt. If you use PowerShell >7 they should work perfectly. 

I used default version installed on my windows 10 machine (ps 5.1), my bad. Glad it works on newer versions.

**Comment by tristanisham** [comment]
@danyildiabin Unfortunately, I don't think it's possible to wrap specific words or strings in color codes with command prompt. You can only set global shell colors like text, background, and borders. I'll keep looking though. 

Did the fix I added to ZVM help at all?

**Comment by voltflake** [comment]
I did some research and figured that all recent windows versions come with ps5.1 installed and are hard to replace properly with newer one.
Found [this](https://superuser.com/questions/1259900/how-to-colorize-the-powershell-prompt) info about coloring in `powershell` and probably old `cmd.exe`. Hope it helps.

**Comment by voltflake** [comment]
> Did the fix I added to ZVM help at all?

Yes, colors can now be switched on/off. Works fine.
